### ISSUE TITLE
Plots on the right side of Topics page are empty

### ISSUE THREAD

**Issue by aleticacr** [x-tabdeveloping/topicwizard#10]
Hi! Thank you for such a useful innovation!
I'm attempting to visualise the topic modelling of 100 short texts (phrases). The code has worked fine, but once I try to visualise, the plots that are supposed to appear on the right side of the Topics page are empty. I thought that less components (i.e., less topics) could make it work, but an additional error comes up in the code when trying with 3 components.

![Screenshot 2023-04-30 at 14 52 26](https://user-images.githubusercontent.com/132203991/235354000-a9ff6f1f-1e65-456a-95e4-6f8f5283d31d.png)

**Comment by x-tabdeveloping** [comment]
Can you give me your logs? Maybe also a reproducible sample of code (and perhaps data if it isn't a GDPR problem), so I can try yo debug.

**Comment by mekomlusa** [comment]
I also ran into the same issue when attempting to visualize the topics generated on short texts. Unfortunately I cannot share the code or data, but the error message seems to hint that it's related to division by 0.

```
ValueError: kth(=200) out of bounds (200)
Exception on /_dash-update-component [POST]
```

```
.../python3.9/site-packages/topicwizard/prepare/topics.py:92: RuntimeWarning:

divide by zero encountered in log
```

**Comment by IvanlSan** [comment]
The same thing happened to me, what I see is that the internet tab where the dasboard is displayed shows the message updating... and it doesn´t finish loading
![git](https://github.com/x-tabdeveloping/topic-wizard/assets/138510079/b4a3fe7d-8179-4f46-863c-3ddac6ca3afa)

**Comment by x-tabdeveloping** [comment]
Can you please provide an error stack trace and also details about what topic model you used with what kind of data? I won't be able to help or fix this bug without further details.

**Comment by x-tabdeveloping** [comment]
Also can you try the standalone plot and see how that behaves?
```python
from topicwizard.figures import topic_barcharts

topic_barcharts(corpus=texts, pipeline=pipeline, top_n=5)
```

**Comment by x-tabdeveloping** [comment]
I believe 0.5.0 fixes this.
