### ISSUE TITLE
How to read the generated graphs?

### ISSUE THREAD

**Issue by gnanukoth** [x-tabdeveloping/topicwizard#11]
Hello,
Can you help me in understanding the generated graph results? As there are no axis labels or legends, I'm finding it difficult to interpret and read the graph. For example, In the Documents visualization, what do the axes in the timeline chart represent? How to read this timeline graph? Similar explanations for other topic and word graphs will also be helpful. Thank you for your work and time!

**Comment by x-tabdeveloping** [comment]
Hello, I think you might find some answers in the documentation (that is a bit outdated I will have to do some changes). Regarding the timeline the x-axis represents windows of N tokens, and the y-axis is the topic distribution at each timepoint. I hope you find this answer useful, I will try to do a better job at documenting this, feel free to ask if you have any further questions. :)

**Comment by x-tabdeveloping** [comment]
Helpers are added to all pages now, this is thoroughly documented
