### ISSUE TITLE
Usable on Colab

### ISSUE THREAD

**Issue by firmai** [x-tabdeveloping/topicwizard#21]
A lot of people have resorted to using Colab for it memory power, it would be great to have a good working example without the conflicts maybe a Colab version.. 

Thanks for this, great work!

**Comment by x-tabdeveloping** [comment]
Hey, thanks for hitting me up about that, I live in my own little terminal land for the most part and tend to forget about such things. I will get to a working Colab example as soon as possible. I think the app should work fine in Colab though. What have you experienced? Can you maybe elaborate on what issues you had?

**Comment by x-tabdeveloping** [comment]
I rewrote the Colab example and it works as it should. Can you please verify @firmai ?

**Comment by firmai** [comment]
Lovely, thanks for that! Working on any new projects or just focusing on maintaining this one?

**Comment by x-tabdeveloping** [comment]
Hey @firmai, I'm currently working mainly on Scandinavian embeddings (benchmark and models) and a contextually sensitive topic modeling framework (turftopic) for which the papers and the Python package are already in progress + making topicwizard compatible with contextual models.
