### ISSUE TITLE
Web app freezes when hovering over (?)

### ISSUE THREAD

**Issue by lbluett** [x-tabdeveloping/topicwizard#23]
Hi x-tab, 

Whenever I hover over the (?) the topicwizard webapp becomes unresponsive.

**Comment by x-tabdeveloping** [comment]
Hello, can you supply me with a bit more information? Which page? What computer are you running it on? Does it say "updating..." in the header? How large a corpus are you using it on? Do you get any logs in the terminal?

**Comment by lbluett** [comment]
Hi, apologies for the delay. I am on the 'Topics' page. I am running Windows 11. No, it does not say updating. My corpus size is 211878 words. No logs.

**Comment by x-tabdeveloping** [comment]
Can you check if it says anything in the Chrome debugger? (Ctrl+Shift+I)
Also what specs does your computer have? Are you sure this is not a performance problem?
I also really recommend that you use WSL for development at all times, that's what my Windows-user colleagues do anyway.
Some stuff on Windows behaves in weird ways, and I can't really account for this as I don't have access the a Windows machine when developing software.

**Comment by lbluett** [comment]
Update: I seem to get an 'Out of Memory' error in my browser.

**Comment by lbluett** [comment]
![image](https://github.com/x-tabdeveloping/topicwizard/assets/85853561/870c8412-fb07-4c64-828a-8bb0e1f785c9)

chrome debugger

**Comment by lbluett** [comment]
Switched to WSL using Ubuntu. Works a charm - thanks for the suggestion!
