### ISSUE TITLE
Error building wheel for pandas

### ISSUE THREAD

**Issue by rdkm89** [x-tabdeveloping/topicwizard#37]
### Current Behavior:
There is a bug when installing dependencies which means that I am unable to install ```topicwizard``` in my environment. 

When installing via ```pip```, the following output appears and then hangs indefinitely:

```bash
Building wheels for collected packages: pandas, jsbeautifier, editorconfig
  Building wheel for pandas (pyproject.toml) ... -
```

Which suggests that the problem is specifically related to ```pandas```.

### Expected Behavior:
```topicwizard``` should install from ```pip``` instead of hanging indefinitely.

### Steps To Reproduce:
On the environment below, run the following:

```bash
pip install --upgrade pip
pip install topic-wizard
```
### Environment:

- OS: Ubuntu 24.04 LTS
- Python 3.12.3

### Anything else:
I suspect that the problem here is due to lack of Python 3.12 support for ```pandas```. 

This appears to have been a problem recently, as discussed [here](https://discuss.python.org/t/python-3-12-1-32-bit-unable-to-pip-install-pandas/42407) - I'm unsure about the current status of support for Python 3.12. But if that is the problem, it could be worth indicating for users that 3.12 is currently not supported by ```topicwizard```.

**Comment by x-tabdeveloping** [comment]
I think you're right. I suspect that the issues arise because older versions of pandas do not support 3.12, while newer versions are not supported by topicwizard, and pip gets into a deadlock. I'm working on it in a PR #38 , as soon as tests pass, I will release a new version.

**Comment by x-tabdeveloping** [comment]
I also added a test for 3.12 just to make sure that everything runs smoothly.

**Comment by x-tabdeveloping** [comment]
Since this is fixed, I'm closing the issue
